// 把适配引擎打成单文件 dist/adapt.mjs。
//
// 桌面端不能直接跑 SDK 源码：CLI 是裸 TS 靠 tsx 执行，而安装包里没有 tsx、
// 也没有 workspace 的 node_modules。所以这里把 jszip / zod / @lingfang/contract
// 全部 inline 进来，产出一个只依赖 node 内置模块的 .mjs，作为 Tauri resource 分发。

import { build } from 'esbuild';
import { mkdir, stat } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const outfile = join(packageRoot, 'dist', 'adapt.mjs');

await mkdir(dirname(outfile), { recursive: true });

const result = await build({
  entryPoints: [join(packageRoot, 'src', 'adapt', 'bin.ts')],
  outfile,
  bundle: true,
  platform: 'node',
  // 与桌面端内置 node 运行时对齐；调低会丢掉 node: 前缀内置模块的解析。
  target: 'node20',
  format: 'esm',
  // node 内置模块保持外部；其余（jszip / zod / @lingfang/contract）一律 inline。
  packages: 'bundle',
  external: ['node:*'],
  // SDK 源码用 `./foo.ts` 显式扩展名 import，esbuild 需要这条才能解析到源文件。
  resolveExtensions: ['.ts', '.mjs', '.js', '.json'],
  banner: {
    js: '// @generated by packages/plugin-sdk/scripts/build-adapt.mjs —— 请勿手改，改源码后重新构建。',
  },
  logLevel: 'warning',
  metafile: false,
  minify: false,
  sourcemap: false,
});

if (result.errors.length > 0) process.exit(1);

const info = await stat(outfile);
process.stdout.write(`adapt.mjs 构建完成：${outfile} (${(info.size / 1024).toFixed(0)} KiB)\n`);
